name: Pre-Commit Check

on:
  pull_request:
    branches:
      - "release/2024.2"

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Checkout the code in the PR branch

    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"  # Use the version you need, for example, 3.10 or 3.12

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pre-commit
      run: |
        pre-commit run --all-files
